# Generated by Django 4.0.4 on 2022-05-23 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CollectionName', models.CharField(max_length=30)),
                ('CollectionDescription', models.TextField()),
                ('Tv', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1)),
                ('Clima', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1)),
                ('Shower', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1)),
                ('Wifi', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1)),
                ('Pool', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1)),
                ('Balcony', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1)),
                ('Breakfast', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1)),
                ('Dinner', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1)),
                ('KingSize', models.IntegerField()),
                ('QueenSize', models.IntegerField()),
                ('SingleSize', models.IntegerField()),
                ('Stars', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomNumber', models.IntegerField()),
                ('RoomImage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('CollectionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApp.collections')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateD', models.DateField()),
                ('DateF', models.DateField()),
                ('Total', models.FloatField()),
                ('ClientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApp.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateD', models.DateField()),
                ('DateF', models.DateField()),
                ('Total', models.FloatField()),
                ('ClientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApp.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FeedbackText', models.TextField()),
                ('ClientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('RoomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApp.rooms')),
            ],
        ),
    ]
